# Generated by Django 6.0.6 on 2026-07-03 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='How your name appears to other family members', max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, help_text='Used for birthday notifications to other family members', null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('pt', 'Português'), ('ar', 'العربية'), ('sw', 'Kiswahili'), ('zh', '中文'), ('hi', 'हिन्दी'), ('de', 'Deutsch'), ('it', 'Italiano'), ('ja', '日本語'), ('ko', '한국어')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone string, e.g. America/New_York', max_length=50)),
                ('theme_preference', models.CharField(choices=[('system', 'Follow System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notify_birthdays_email', models.BooleanField(default=True)),
                ('notify_birthdays_push', models.BooleanField(default=True)),
                ('notify_new_member_email', models.BooleanField(default=True)),
                ('notify_change_requests_email', models.BooleanField(default=True)),
                ('notify_photo_tags_email', models.BooleanField(default=True)),
                ('notify_invitations_email', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('linked_member', models.OneToOneField(blank=True, help_text='The family member record this account belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_by_profile', to='tree.familymember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
