# Generated by Django 6.0.6 on 2026-07-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='digest_frequency',
            field=models.CharField(choices=[('instant', 'Instant (Important Only)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_birthdays_email',
            field=models.BooleanField(default=False, help_text='Receive emails for family birthdays (In-App notification always active)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_change_requests_email',
            field=models.BooleanField(default=True, help_text='Receive emails for pending change requests needing your approval'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_invitations_email',
            field=models.BooleanField(default=True, help_text='Receive emails when invited to join a family tree'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_new_member_email',
            field=models.BooleanField(default=False, help_text='Receive emails when new members are added'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_photo_tags_email',
            field=models.BooleanField(default=False, help_text='Receive emails when tagged in a photo'),
        ),
    ]
