# Generated by Django 6.0.6 on 2026-07-03 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='tree.familymember')),
            ],
            options={
                'verbose_name': 'History Event (Legacy)',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('invite', 'Invited'), ('login', 'Logged In')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, help_text='JSON diff of before/after values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='history_aud_model_n_126f60_idx'), models.Index(fields=['user', '-timestamp'], name='history_aud_user_id_dc3aef_idx')],
            },
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', '🍼 Birth'), ('baptism', '⛪ Baptism / Naming Ceremony'), ('childhood', '👦 Childhood'), ('education', '🎓 Education'), ('graduation', '🎓 Graduation'), ('career', '💼 Career'), ('military', '🎖️ Military Service'), ('marriage', '💍 Marriage'), ('divorce', '📄 Divorce / Separation'), ('engagement', '💎 Engagement'), ('child_born', '👶 Child Born'), ('adoption', '🏠 Adoption'), ('moved', '📍 Moved / Relocated'), ('emigrated', '✈️ Emigrated'), ('immigrated', '🛬 Immigrated'), ('award', '🏆 Award / Honor'), ('publication', '📚 Publication'), ('founded', '🏗️ Founded Organization'), ('illness', '🏥 Illness'), ('recovery', '💪 Recovery'), ('religious', '🕌 Religious Milestone'), ('cultural', '🎭 Cultural Milestone'), ('retirement', '🌅 Retirement'), ('death', '⚰️ Death'), ('memorial', '🕯️ Memorial'), ('other', '📌 Other')], max_length=30)),
                ('title', models.CharField(help_text='Short event title, e.g. "Graduated from University of Kinshasa"', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_is_approximate', models.BooleanField(default=False, help_text='If true, date is approximate (circa)')),
                ('date_display', models.CharField(blank=True, help_text='Custom date display, e.g. "Spring 1945"', max_length=100)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='life_events/')),
                ('document', models.FileField(blank=True, null=True, upload_to='life_events/docs/')),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('family', 'Family Only'), ('close_family', 'Close Family'), ('private', 'Private')], default='family', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='tree.familymember')),
            ],
            options={
                'verbose_name': 'Life Event',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['member', 'date'], name='history_lif_member__630518_idx'), models.Index(fields=['event_type'], name='history_lif_event_t_db4eb9_idx')],
            },
        ),
    ]
