# Generated by Django 6.0.6 on 2026-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='show_age',
            field=models.BooleanField(default=True, help_text="Whether to show calculated age on this member's profile"),
        ),
    ]
