# Generated by Django 5.2.4 on 2025-08-07 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='dod',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='bio',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='dob',
        ),
        migrations.AddField(
            model_name='familymember',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
