# Generated by Django 6.0.6 on 2026-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_familymember_show_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='crest_caption',
            field=models.CharField(blank=True, help_text='Optional family motto or crest description', max_length=255),
        ),
        migrations.AddField(
            model_name='tree',
            name='crest_image',
            field=models.ImageField(blank=True, help_text='Family crest, coat of arms, or clan emblem (max 2MB)', null=True, upload_to='crests/'),
        ),
        migrations.AddField(
            model_name='tree',
            name='theme_dark',
            field=models.CharField(blank=True, help_text='Dark hex color for text-on-light use', max_length=7),
        ),
        migrations.AddField(
            model_name='tree',
            name='theme_light',
            field=models.CharField(blank=True, help_text='Light/background hex color', max_length=7),
        ),
        migrations.AddField(
            model_name='tree',
            name='theme_mid',
            field=models.CharField(blank=True, help_text='Mid-tone hex color for gradients', max_length=7),
        ),
        migrations.AddField(
            model_name='tree',
            name='theme_preset',
            field=models.CharField(blank=True, default='emerald_root', help_text='Slug of the chosen preset palette (e.g. "savanna_gold")', max_length=60),
        ),
        migrations.AddField(
            model_name='tree',
            name='theme_primary',
            field=models.CharField(blank=True, help_text='Primary hex color, e.g. #15803d', max_length=7),
        ),
    ]
