# Generated by Django 5.2.7 on 2026-01-26 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_rename_dod_familymember_death_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of this family tree'),
        ),
        migrations.AddField(
            model_name='tree',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public'), ('shared', 'Shared'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('primary', 'Primary Family'), ('maternal', 'Maternal Line'), ('paternal', 'Paternal Line'), ('extended', 'Extended Family'), ('adopted', 'Adopted Family'), ('step', 'Step Family'), ('other', 'Other')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='tree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TreePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('guest', 'Guest')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tree.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tree', 'user')},
            },
        ),
    ]
