"""
tree/calendar_utils.py — Standard RFC 5545 iCalendar (.ics) Generator for La Racine

Generates strict RFC 5545 iCalendar (.ics) files for:
- Member Birthdays (RRULE yearly recurring)
- Marriages / Anniversaries (RRULE yearly recurring)
- Memorial Days (RRULE yearly recurring)
- Custom Family Events (Reunions, Gatherings, Ceremonies)

Features line folding (RFC 5545 Section 3.1) and UTF-8 escaping.
"""

from datetime import datetime, date
from django.utils import timezone


def escape_ical_text(text):
    """Escape special characters in iCalendar field text according to RFC 5545."""
    if not text:
        return ''
    text = str(text)
    text = text.replace('\\', '\\\\')
    text = text.replace(';', '\\;')
    text = text.replace(',', '\\,')
    text = text.replace('\n', '\\n')
    text = text.replace('\r', '')
    return text


def fold_line(line):
    """
    Folds lines longer than 75 octets according to RFC 5545 Section 3.1.
    Subsequent lines begin with a single space.
    """
    if len(line.encode('utf-8')) <= 75:
        return line

    encoded = line.encode('utf-8')
    chunks = []
    i = 0
    max_len = 75
    while i < len(encoded):
        chunk = encoded[i:i + max_len].decode('utf-8', errors='ignore')
        chunks.append(chunk)
        i += len(chunk.encode('utf-8'))
        max_len = 74 # 1 space prefix on folded continuation lines

    return '\r\n '.join(chunks)


def format_ical_date(dt, all_day=True):
    """Format a python date, datetime, or ISO date string into RFC 5545 format."""
    if isinstance(dt, str):
        try:
            # Try parsing ISO datetime string or YYYY-MM-DD
            if 'T' in dt:
                dt = datetime.fromisoformat(dt.replace('Z', '+00:00'))
            else:
                dt = datetime.strptime(dt[:10], '%Y-%m-%d').date()
        except ValueError:
            return ''

    if isinstance(dt, datetime):
        return dt.strftime('%Y%m%dT%H%M%SZ')
    elif isinstance(dt, date):
        return dt.strftime('%Y%m%d')
    return ''


def build_ics_feed(tree_name, events_list):
    """
    Builds a full, strict RFC 5545 .ics text string with proper line folding.

    events_list items:
    {
        'uid': 'unique-id-str',
        'title': 'John Doe\'s 45th Birthday',
        'description': 'Description text',
        'start_date': date, datetime, or ISO str,
        'end_date': date, datetime, or ISO str (optional),
        'all_day': bool,
        'is_recurring': bool,
        'category': 'Birthday' | 'Anniversary' | 'Memorial' | 'Event',
        'location': 'Location string' (optional)
    }
    """
    raw_lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//La Racine//Family Tree Calendar 2.0//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        f'X-WR-CALNAME:{escape_ical_text(tree_name + " — Family Calendar")}',
        'X-WR-CALDESC:Family birthdays, anniversaries, and gatherings generated by La Racine.',
        'X-WR-TIMEZONE:UTC',
    ]

    now_str = timezone.now().strftime('%Y%m%dT%H%M%SZ')

    for ev in events_list:
        raw_lines.append('BEGIN:VEVENT')
        raw_lines.append(f'UID:{ev.get("uid")}')
        raw_lines.append(f'DTSTAMP:{now_str}')
        raw_lines.append('STATUS:CONFIRMED')

        all_day = ev.get('all_day', True)
        start_date = ev.get('start_date')

        if start_date:
            d_str = format_ical_date(start_date, all_day=all_day)
            if d_str:
                if all_day:
                    raw_lines.append(f'DTSTART;VALUE=DATE:{d_str[:8]}')
                else:
                    raw_lines.append(f'DTSTART:{d_str}')

        end_date = ev.get('end_date')
        if end_date:
            d_end_str = format_ical_date(end_date, all_day=all_day)
            if d_end_str:
                if all_day:
                    raw_lines.append(f'DTEND;VALUE=DATE:{d_end_str[:8]}')
                else:
                    raw_lines.append(f'DTEND:{d_end_str}')

        summary = escape_ical_text(ev.get("title", "Family Event"))
        if ev.get('kinship_label') and ev.get('kinship_label') != 'Family Event':
            summary += f' ({escape_ical_text(ev.get("kinship_label"))})'
        raw_lines.append(f'SUMMARY:{summary}')

        if ev.get('description'):
            raw_lines.append(f'DESCRIPTION:{escape_ical_text(ev.get("description"))}')

        if ev.get('location'):
            raw_lines.append(f'LOCATION:{escape_ical_text(ev.get("location"))}')

        if ev.get('category'):
            raw_lines.append(f'CATEGORIES:{escape_ical_text(ev.get("category"))}')

        if ev.get('is_recurring', True):
            raw_lines.append('RRULE:FREQ=YEARLY')

        raw_lines.append('END:VEVENT')

    raw_lines.append('END:VCALENDAR')

    # Apply RFC 5545 line folding
    folded_lines = [fold_line(l) for l in raw_lines]
    return '\r\n'.join(folded_lines)
