"""
tree/calendar_utils.py — RFC 5545 iCalendar (.ics) Generator for La Racine

Generates standard iCalendar (.ics) format files for:
- Member Birthdays (RRULE yearly recurring)
- Marriages / Anniversaries (RRULE yearly recurring)
- Memorial Days (RRULE yearly recurring)
- Custom Family Events (Reunions, Gatherings, Ceremonies)
"""

from datetime import datetime, date
from django.utils import timezone


def escape_ical_text(text):
    """Escape special characters in iCalendar field text according to RFC 5545."""
    if not text:
        return ''
    text = str(text)
    text = text.replace('\\', '\\\\')
    text = text.replace(';', '\\;')
    text = text.replace(',', '\\,')
    text = text.replace('\n', '\\n')
    text = text.replace('\r', '')
    return text


def format_ical_date(dt, all_day=True):
    """Format a python date or datetime into RFC 5545 string."""
    if isinstance(dt, datetime):
        return dt.strftime('%Y%m%dT%H%M%SZ')
    elif isinstance(dt, date):
        return dt.strftime('%Y%m%d')
    return ''


def build_ics_feed(tree_name, events_list):
    """
    Builds a full RFC 5545 .ics text string.

    events_list items:
    {
        'uid': 'unique-id-str',
        'title': 'John Doe\'s 45th Birthday',
        'description': 'Description text',
        'start_date': date or datetime object,
        'end_date': date or datetime object (optional),
        'all_day': bool,
        'is_recurring': bool,
        'category': 'Birthday' | 'Anniversary' | 'Memorial' | 'Event',
        'location': 'Location string' (optional)
    }
    """
    lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//La Racine//Family Tree Calendar//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        f'X-WR-CALNAME:{escape_ical_text(tree_name + " — Family Calendar")}',
        'X-WR-CALDESC:Family tree birthdays, anniversaries, and family events generated by La Racine.',
        'X-WR-TIMEZONE:UTC',
    ]

    now_str = timezone.now().strftime('%Y%m%dT%H%M%SZ')

    for ev in events_list:
        lines.append('BEGIN:VEVENT')
        lines.append(f'UID:{ev.get("uid")}')
        lines.append(f'DTSTAMP:{now_str}')

        all_day = ev.get('all_day', True)
        start_date = ev.get('start_date')

        if all_day and isinstance(start_date, (date, datetime)):
            d_str = format_ical_date(start_date, all_day=True)[:8]
            lines.append(f'DTSTART;VALUE=DATE:{d_str}')
        elif isinstance(start_date, datetime):
            lines.append(f'DTSTART:{format_ical_date(start_date, all_day=False)}')

        end_date = ev.get('end_date')
        if end_date:
            if all_day and isinstance(end_date, (date, datetime)):
                d_str = format_ical_date(end_date, all_day=True)[:8]
                lines.append(f'DTEND;VALUE=DATE:{d_str}')
            elif isinstance(end_date, datetime):
                lines.append(f'DTEND:{format_ical_date(end_date, all_day=False)}')

        lines.append(f'SUMMARY:{escape_ical_text(ev.get("title", "Family Event"))}')

        if ev.get('description'):
            lines.append(f'DESCRIPTION:{escape_ical_text(ev.get("description"))}')

        if ev.get('location'):
            lines.append(f'LOCATION:{escape_ical_text(ev.get("location"))}')

        if ev.get('category'):
            lines.append(f'CATEGORIES:{escape_ical_text(ev.get("category"))}')

        if ev.get('is_recurring', True):
            lines.append('RRULE:FREQ=YEARLY')

        lines.append('END:VEVENT')

    lines.append('END:VCALENDAR')
    return '\r\n'.join(lines)
